import type {
  Achievement,
  BuildingDefinition,
  BuildingKind,
  ObjectiveDefinition,
  ScenarioDefinition,
  ScenarioId,
} from "./types.ts";

export const GRID_COLUMNS = 8;
export const GRID_ROWS = 6;

export const SCENARIOS: Record<ScenarioId, ScenarioDefinition> = {
  growth: {
    id: "growth",
    name: "Steady Growth",
    difficulty: "Standard",
    description: "Build from a modest starter stack while traffic rises at a predictable pace.",
    startingMoney: 28500,
    baseTraffic: 42,
    trafficGrowth: 0.17,
    waveTraffic: 18,
    incidentRisk: 1,
    revenueMultiplier: 1,
  },
  "launch-day": {
    id: "launch-day",
    name: "Launch Day",
    difficulty: "Advanced",
    description: "A high-profile release sends demand climbing fast. Scale ahead of each wave.",
    startingMoney: 34000,
    baseTraffic: 58,
    trafficGrowth: 0.25,
    waveTraffic: 26,
    incidentRisk: 1.2,
    revenueMultiplier: 1.16,
  },
  "chaos-lab": {
    id: "chaos-lab",
    name: "Chaos Lab",
    difficulty: "Expert",
    description: "Frequent failures put observability, redundancy, and your reserve budget to the test.",
    startingMoney: 32000,
    baseTraffic: 46,
    trafficGrowth: 0.2,
    waveTraffic: 20,
    incidentRisk: 1.8,
    revenueMultiplier: 1.1,
  },
};

export const SCENARIO_LIST = Object.values(SCENARIOS);

export const BUILDINGS: Record<BuildingKind, BuildingDefinition> = {
  dns: {
    kind: "dns",
    name: "DNS Exchange",
    shortName: "DNS",
    code: "DX",
    category: "Edge",
    role: "Directs incoming traffic to your city.",
    description: "The public address book for your stack.",
    concept: "DNS translates a human-friendly domain into the network address that serves it.",
    color: "#6ee7ff",
    cost: 1800,
    upkeep: 42,
    capacity: 500,
    latency: 12,
    reliability: 0.998,
    unlockRank: 1,
  },
  cdn: {
    kind: "cdn",
    name: "CDN Outpost",
    shortName: "CDN",
    code: "CD",
    category: "Edge",
    role: "Serves static traffic close to users.",
    description: "Offloads frontend work and cuts latency.",
    concept: "A CDN caches static assets at edge locations so fewer requests reach the origin.",
    color: "#45f0bd",
    cost: 4600,
    upkeep: 115,
    capacity: 170,
    latency: -24,
    reliability: 0.999,
    unlockRank: 2,
  },
  frontend: {
    kind: "frontend",
    name: "Web Tower",
    shortName: "Web",
    code: "WEB",
    category: "Compute",
    role: "Renders the experience users see.",
    description: "Your city’s public-facing application.",
    concept: "Frontend servers turn requests into the interface delivered to a browser.",
    color: "#8be95d",
    cost: 3200,
    upkeep: 100,
    capacity: 115,
    latency: 34,
    reliability: 0.992,
    unlockRank: 1,
  },
  loadBalancer: {
    kind: "loadBalancer",
    name: "Traffic Hub",
    shortName: "Balancer",
    code: "LB",
    category: "Edge",
    role: "Spreads requests across duplicate services.",
    description: "Makes horizontal scaling effective.",
    concept: "A load balancer distributes traffic and avoids sending everything to one server.",
    color: "#ffd166",
    cost: 3900,
    upkeep: 105,
    capacity: 420,
    latency: 8,
    reliability: 0.997,
    unlockRank: 2,
  },
  api: {
    kind: "api",
    name: "API Factory",
    shortName: "API",
    code: "API",
    category: "Compute",
    role: "Runs application and business logic.",
    description: "The core compute layer of the stack.",
    concept: "API servers validate requests, apply business rules, and coordinate data services.",
    color: "#ff9f43",
    cost: 4200,
    upkeep: 150,
    capacity: 82,
    latency: 62,
    reliability: 0.988,
    unlockRank: 1,
  },
  auth: {
    kind: "auth",
    name: "Identity Hall",
    shortName: "Auth",
    code: "ID",
    category: "Platform",
    role: "Validates identities and permissions.",
    description: "Protects traffic before it reaches data.",
    concept: "Authentication confirms identity; authorization decides which actions are allowed.",
    color: "#bd93ff",
    cost: 4400,
    upkeep: 135,
    capacity: 180,
    latency: 18,
    reliability: 0.995,
    unlockRank: 2,
  },
  cache: {
    kind: "cache",
    name: "Cache Depot",
    shortName: "Cache",
    code: "C",
    category: "Data",
    role: "Keeps frequently used data close at hand.",
    description: "Reduces database load and response time.",
    concept: "A cache trades some freshness and memory for lower latency and less database work.",
    color: "#5ce1e6",
    cost: 3600,
    upkeep: 95,
    capacity: 155,
    latency: -48,
    reliability: 0.985,
    unlockRank: 1,
  },
  database: {
    kind: "database",
    name: "Data Vault",
    shortName: "Database",
    code: "DB",
    category: "Data",
    role: "Stores durable application records.",
    description: "Essential, stateful, and expensive to overload.",
    concept: "A database persists structured state and is often the hardest layer to scale safely.",
    color: "#4dabf7",
    cost: 5600,
    upkeep: 210,
    capacity: 70,
    latency: 88,
    reliability: 0.99,
    unlockRank: 1,
  },
  queue: {
    kind: "queue",
    name: "Queue Station",
    shortName: "Queue",
    code: "Q",
    category: "Platform",
    role: "Buffers work during demand spikes.",
    description: "Turns sudden bursts into manageable flow.",
    concept: "A message queue decouples producers from consumers and preserves work until workers are ready.",
    color: "#ff7eb6",
    cost: 4100,
    upkeep: 120,
    capacity: 240,
    latency: 14,
    reliability: 0.996,
    unlockRank: 3,
  },
  worker: {
    kind: "worker",
    name: "Worker Plant",
    shortName: "Worker",
    code: "WK",
    category: "Compute",
    role: "Processes background jobs asynchronously.",
    description: "Drains queues without blocking users.",
    concept: "Workers pull jobs from queues so slow tasks can run outside the request path.",
    color: "#f78c6c",
    cost: 3800,
    upkeep: 125,
    capacity: 105,
    latency: 0,
    reliability: 0.986,
    unlockRank: 3,
  },
  storage: {
    kind: "storage",
    name: "Storage Yard",
    shortName: "Storage",
    code: "S3",
    category: "Data",
    role: "Holds files, images, and large objects.",
    description: "Moves heavy blobs out of the database.",
    concept: "Object storage is optimized for durable files rather than relational queries.",
    color: "#a3e635",
    cost: 3500,
    upkeep: 88,
    capacity: 260,
    latency: 28,
    reliability: 0.999,
    unlockRank: 3,
  },
  search: {
    kind: "search",
    name: "Search Works",
    shortName: "Search",
    code: "SRCH",
    category: "Data",
    role: "Answers full-text queries quickly.",
    description: "A specialized index for discovery workloads.",
    concept: "Search services maintain indexes that are optimized for relevance and text retrieval.",
    color: "#f9e2af",
    cost: 5200,
    upkeep: 165,
    capacity: 135,
    latency: 22,
    reliability: 0.991,
    unlockRank: 4,
  },
  monitoring: {
    kind: "monitoring",
    name: "Watchtower",
    shortName: "Monitor",
    code: "OBS",
    category: "Platform",
    role: "Reveals faults and shortens incidents.",
    description: "Adds observability and safer operations.",
    concept: "Metrics, logs, and traces make system behavior visible before users report a failure.",
    color: "#ffdf6c",
    cost: 2800,
    upkeep: 82,
    capacity: 999,
    latency: 0,
    reliability: 0.999,
    unlockRank: 1,
  },
};

export const BUILDING_LIST = Object.values(BUILDINGS);

export const RANKS = [
  { name: "Garage Hacker", xp: 0 },
  { name: "Systems Builder", xp: 900 },
  { name: "Scale Engineer", xp: 2600 },
  { name: "Reliability Lead", xp: 5600 },
  { name: "Cloud Architect", xp: 10500 },
];

export const OBJECTIVES: ObjectiveDefinition[] = [
  {
    id: "route",
    title: "Open the route",
    description: "Keep Web, API, and Database connected for 45 RPS.",
    reward: 1800,
    xp: 250,
  },
  {
    id: "cache",
    title: "Cut the round trip",
    description: "Build and connect a Cache Depot.",
    reward: 2200,
    xp: 350,
  },
  {
    id: "satisfaction",
    title: "Earn user trust",
    description: "Raise satisfaction to 88% or higher.",
    reward: 2600,
    xp: 450,
  },
  {
    id: "observability",
    title: "See the system",
    description: "Build and connect a Watchtower.",
    reward: 3000,
    xp: 550,
  },
  {
    id: "scale",
    title: "Handle the rush",
    description: "Serve at least 115 RPS with under 3% errors.",
    reward: 3800,
    xp: 700,
  },
  {
    id: "async",
    title: "Go asynchronous",
    description: "Connect a Queue Station and Worker Plant.",
    reward: 4500,
    xp: 900,
  },
  {
    id: "availability",
    title: "Four nines? Start here.",
    description: "Hold 99% availability while serving 150 RPS.",
    reward: 6000,
    xp: 1250,
  },
  {
    id: "city",
    title: "Build the city",
    description: "Serve 210 RPS with an architecture score of 80.",
    reward: 10000,
    xp: 2200,
  },
];

export const ACHIEVEMENT_CATALOG: Achievement[] = [
  { id: "first-build", name: "Groundbreaking", description: "Place your first new service." },
  { id: "first-link", name: "Handshake", description: "Create a new connection." },
  { id: "speedy", name: "Fast Path", description: "Reach sub-140 ms latency." },
  { id: "cache-hero", name: "Cache Money", description: "Reach a 50% cache hit rate." },
  { id: "six-figures", name: "Traffic Jam", description: "Serve more than 100 RPS." },
  { id: "reliable", name: "Green Across the Board", description: "Reach 99% availability." },
  { id: "incident", name: "On Call", description: "Resolve your first incident." },
  { id: "redundant", name: "No Single Point", description: "Run duplicate API and Database services." },
  { id: "architect", name: "Well Architected", description: "Reach an architecture score of 80." },
  { id: "campaign", name: "Mayor of the Stack", description: "Complete every campaign objective." },
];

export const INCIDENTS = [
  { title: "CPU saturation", message: "A hot deployment is starving request workers.", severity: "warning" as const },
  { title: "Dependency timeout", message: "Downstream calls are waiting past their deadline.", severity: "critical" as const },
  { title: "Connection pool exhausted", message: "New data connections cannot be opened.", severity: "critical" as const },
  { title: "Memory pressure", message: "Evictions and retries are increasing latency.", severity: "warning" as const },
  { title: "Packet loss", message: "Intermittent network loss is forcing retries.", severity: "warning" as const },
  { title: "Cache stampede", message: "Many requests are rebuilding the same expired value.", severity: "critical" as const },
];
